name: CMake Build and Upload

on: [push]

jobs:
  build:
    permissions: write-all
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
          artifact: "hello_world.tar.gz",
          compression_method: "czfv",
          cxx: msvc,
          name: "Windows Latest MSVC",
          os: windows-latest,
          platform: "windows"
        }
        - {
          artifact: "hello_world.tar.xz",
          compression_method: "cJfv",
          cxx: clang++,
          name: "Ubuntu Latest CLANG",
          os: ubuntu-latest,
          platform: "ubuntu"
        }
    
    steps:
    - uses: actions/checkout@v4.1.0

    - name: Configure CMake ${{ matrix.config.platform }}
      env:
        CXX: ${{ matrix.config.cxx }}
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install/

    - name: Build
      run: cmake --build build --config Release

    - name: Install
      run: | 
        mkdir -p ${{github.workspace}}/install
        cmake --install build --prefix ${{github.workspace}}/install/ --strip --config Release

    - name: Debug
      working-directory: ${{github.workspace}}
      run: |
        ls 
        cd install
        ls   

    - name: Pack release
      working-directory: ${{github.workspace}}/install/
      run: |
        ls | echo
        cmake -E tar ${{ matrix.config.compression_method }} ../${{ matrix.config.artifact }} $(find . -type f -printf '%f\n')

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ matrix.config.os }}-${{ github.ref_name }}"
        title: "${{ matrix.config.os }} ${{ github.ref_name}}"
        files: ./${{ matrix.config.artifact }}
