name: CMake Build and Upload

on: [push]

jobs:
  build:
    permissions: write-all
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
          artifact: "hello_world.tar.gz",
          compression_method: "czfv",
          cxx: msvc,
          name: "Windows Latest MSVC",
          os: windows-latest,
          platform: "windows",
        }
        - {
          artifact: "hello_world.tar.xz",
          compression_method: "cJfv",
          cxx: clang++,
          name: "Ubuntu Latest CLANG",
          os: ubuntu-latest,
          platform: "ubuntu",
        }
    
    steps:
    - uses: actions/checkout@v3.5.0

    - name: Configure CMake ${{ matrix.config.platform }}
      env:
        CXX: ${{ matrix.config.cxx }}
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install/

    - name: Build
      run: cmake --build build --config Release

    - name: Install
      run: cmake --install build --prefix ${{github.workspace}}/install/ --strip

    - name: Debug
      working-directory: ${{github.workspace}}
      run: |
        ls | echo
        echo "Working Directory: $PWD"    

    - name: Pack release
      working-directory: ${{github.workspace}}
      run: |
        ls | echo
        cmake -E tar ${{ matrix.config.compression_method }} ../${{ matrix.config.artifact }} $(find . -type f -printf '%f\n')

    # - uses: "marvinpinto/action-automatic-releases@latest"
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: "${{ matrix.config.os }}-${{ github.ref_name }}"
    #     title: "${{ matrix.config.os }} ${{ github.ref_name}}"
    #     files: ./${{ matrix.config.artifact }}

    - name: Upload to Release Action
      # You may pin to the exact commit or the version.
      # uses: Shopify/upload-to-release@9942a4c936dab172f7101dcc7dc20528ea949102
      uses: Shopify/upload-to-release@v1.0.1
      with:
        name: "${{ matrix.config.os }} ${{ github.ref_name}}"
        path: ./${{ matrix.config.artifact }}
        # Content type for the file
        # content-type: # optional, default is application/octet-stream
        repo-token: "${{ secrets.GITHUB_TOKEN }}"